// Central export for all contract ABIs and address helpers
// Auto-generated by scripts/sync-abis.sh

import eventManager from "./EventManager.json";
import ticketManager from "./TicketManager.json";
import marketplace from "./Marketplace.json";
import platformToken from "./PlatformToken.json";
import tokenSwap from "./TokenSwap.json";
import showManager from "./ShowManager.json";
import didRegistry from "./DIDRegistry.json";

export const ABIS = {
  eventManager: eventManager,
  ticketManager: ticketManager,
  marketplace: marketplace,
  platformToken: platformToken,
  tokenSwap: tokenSwap,
  showManager: showManager,
  didRegistry: didRegistry,
} as const;

// 环境变量命名以 _ADDRESS 结尾，这里统一映射
export const CONTRACT_ADDRESSES = {
  eventManager: import.meta.env.VITE_EVENT_MANAGER_ADDRESS as
    | `0x${string}`
    | undefined,
  ticketManager: import.meta.env.VITE_TICKET_MANAGER_ADDRESS as
    | `0x${string}`
    | undefined,
  marketplace: import.meta.env.VITE_MARKETPLACE_ADDRESS as
    | `0x${string}`
    | undefined,
  platformToken: import.meta.env.VITE_PLATFORM_TOKEN_ADDRESS as
    | `0x${string}`
    | undefined,
  tokenSwap: import.meta.env.VITE_TOKEN_SWAP_ADDRESS as
    | `0x${string}`
    | undefined,
  showManager: import.meta.env.VITE_SHOW_MANAGER_ADDRESS as
    | `0x${string}`
    | undefined,
  didRegistry: import.meta.env.VITE_DID_REGISTRY_ADDRESS as
    | `0x${string}`
    | undefined,
} as const;

export function getAddress(
  key: keyof typeof CONTRACT_ADDRESSES,
  chainId?: number
): `0x${string}` | undefined {
  try {
    const mappingRaw = import.meta.env.VITE_CONTRACTS_JSON;
    if (chainId && mappingRaw) {
      const parsed = JSON.parse(mappingRaw);
      const networkConfig = parsed[String(chainId)];
      if (networkConfig) {
        const upper = key.toUpperCase();
        return (
          networkConfig[upper] || networkConfig[key] || CONTRACT_ADDRESSES[key]
        );
      }
    }
    return CONTRACT_ADDRESSES[key];
  } catch (e) {
    console.warn("Failed parsing VITE_CONTRACTS_JSON", e);
    return CONTRACT_ADDRESSES[key];
  }
}
