// Central export for all contract ABIs and address helpers
// Auto-generated by scripts/sync-abis.sh

import eventManager from './EventManager.json';
import ticketManager from './TicketManager.json';
import marketplace from './Marketplace.json';
import platformToken from './PlatformToken.json';
import tokenSwap from './TokenSwap.json';
import showManager from './ShowManager.json';
import didRegistry from './DIDRegistry.json';

export const ABIS = {
  eventManager: eventManager as const,
  ticketManager: ticketManager as const,
  marketplace: marketplace as const,
  platformToken: platformToken as const,
  tokenSwap: tokenSwap as const,
  showManager: showManager as const,
  didRegistry: didRegistry as const,
};

export const CONTRACT_ADDRESSES = {
  eventManager: import.meta.env.VITE_EVENT_MANAGER as `0x${string}` | undefined,
  ticketManager: import.meta.env.VITE_TICKET_MANAGER as `0x${string}` | undefined,
  marketplace: import.meta.env.VITE_MARKETPLACE as `0x${string}` | undefined,
  platformToken: import.meta.env.VITE_PLATFORM_TOKEN as `0x${string}` | undefined,
  tokenSwap: import.meta.env.VITE_TOKEN_SWAP as `0x${string}` | undefined,
  showManager: import.meta.env.VITE_SHOW_MANAGER as `0x${string}` | undefined,
  didRegistry: import.meta.env.VITE_DID_REGISTRY as `0x${string}` | undefined,
} as const;

export function getAddress(key: keyof typeof CONTRACT_ADDRESSES, chainId?: number): `0x${string}` | undefined {
  try {
    const mappingRaw = import.meta.env.VITE_CONTRACTS_JSON;
    if (chainId && mappingRaw) {
      const parsed = JSON.parse(mappingRaw);
      const networkConfig = parsed[String(chainId)];
      if (networkConfig) {
        const upper = key.toUpperCase();
        return networkConfig[upper] || networkConfig[key] || CONTRACT_ADDRESSES[key];
      }
    }
    return CONTRACT_ADDRESSES[key];
  } catch (e) {
    console.warn('Failed parsing VITE_CONTRACTS_JSON', e);
    return CONTRACT_ADDRESSES[key];
  }
}
